name: Version update

on:
  repository_dispatch:
    types: [version_update]
  workflow_dispatch:

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  log_message:
    #    if: ${{ !github.event.client_payload.passed }}
    runs-on: ubuntu-latest
    steps:
      - name: print message
        run: echo ${{ github.event.client_payload.message }}
